import random
import threading
from PySide6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QStackedWidget,
    QScrollArea, QFrame, QLineEdit, QComboBox, QSpinBox, QFontDialog
)
from PySide6.QtCore import Qt, QTimer, Signal

from core.config import _CFG, _c, save_config, GEMINI_MODELS
from core.database import save_questions
from ui.animations import AnimatedPage, fade_in_widget
from ui.widgets import Card, Sep, PBtn, GBtn, TogBtn, OptBtn, PBar, PulseDot
from logic.worker import GeminiWorker

class DashboardPage(AnimatedPage):
    go = Signal(str)
    def __init__(self, questions, parent=None):
        super().__init__(parent)
        self.questions = questions
        self._build()
    def _build(self):
        outer = self.lay
        outer.setContentsMargins(32, 32, 32, 32)
        outer.setSpacing(20)
        hr = QHBoxLayout()
        ht = QLabel("Dashboard")
        ht.setStyleSheet(f"font-size:20px;font-weight:500;color:{_c('text_pri')};letter-spacing:-0.5px;border:none;background:transparent;")
        hr.addWidget(ht)
        hr.addStretch()
        bl = QLabel(f"{len(self.questions)} questões salvas")
        bl.setStyleSheet(f"font-size:11px;color:{_c('text_mut')};background:{_c('surface')};padding:4px 10px;border-radius:6px;border:1px solid {_c('border')};")
        hr.addWidget(bl)
        outer.addLayout(hr)
        cats = {}
        for q in self.questions:
            c = q.get("categoria", "Geral")
            cats[c] = cats.get(c, 0) + 1
        dif = sum(1 for q in self.questions if q.get("dificuldade") == "dificil")
        sr = QHBoxLayout()
        sr.setSpacing(14)
        for ic, num, lb in [("Total", str(len(self.questions)), "Banco Local"), ("Categorias", str(len(cats)), "Tópicos"), ("Difíceis", str(dif), "Questões"), ("Rodada", str(_CFG.get("questions_per_round", 5)), "Questões por vez")]:
            card = Card(radius=10, pad=16)
            card.setFixedHeight(94)
            card.layout().setSpacing(2)
            for txt, style in [(ic, f"font-size:11px;color:{_c('text_mut')};background:transparent;border:none;"), (num, f"font-size:24px;font-weight:400;color:{_c('text_pri')};border:none;background:transparent;"), (lb, f"font-size:10px;color:{_c('text_dim')};border:none;background:transparent;")]:
                l = QLabel(txt)
                l.setStyleSheet(style)
                card.layout().addWidget(l)
            sr.addWidget(card)
        outer.addLayout(sr)
        cr = QHBoxLayout()
        cr.setSpacing(14)
        for icon_txt, title_txt, desc_txt, btn_txt, sig_key, color in [("📝", "Simulado Local", "Teste conhecimentos usando o\nbanco de dados offline.", "Iniciar Teste", "simulado", None), ("✦", "Gerador IA", "Conecte-se ao Gemini para\ncriar perguntas inéditas.", "Conectar IA", "simulado_ia", _c("accent"))]:
            card = Card(pad=20)
            card.layout().setSpacing(10)
            il = QLabel(icon_txt)
            il.setStyleSheet(f"font-size:20px;background:transparent;border:none;" + (f"color:{color};" if color else f"color:{_c('text_mut')};"))
            card.layout().addWidget(il)
            tl2 = QLabel(title_txt)
            tl2.setStyleSheet(f"font-size:14px;font-weight:500;color:{_c('text_pri')};border:none;background:transparent;")
            card.layout().addWidget(tl2)
            dl = QLabel(desc_txt)
            dl.setStyleSheet(f"font-size:12px;color:{_c('text_mut')};line-height:1.4;border:none;background:transparent;")
            card.layout().addWidget(dl)
            card.layout().addStretch()
            b = PBtn(btn_txt, color=color)
            b.setFixedWidth(130)
            b.clicked.connect(lambda _, k=sig_key: self.go.emit(k))
            card.layout().addWidget(b)
            cr.addWidget(card, 1)
        cats_card = Card(pad=18)
        cats_card.layout().setSpacing(8)
        ctl = QLabel("Resumo de Categorias")
        ctl.setStyleSheet(f"font-size:13px;font-weight:500;color:{_c('text_pri')};border:none;background:transparent;")
        cats_card.layout().addWidget(ctl)
        cats_card.layout().addSpacing(4)
        sorted_cats = sorted(cats.items(), key=lambda x: x[1], reverse=True)
        total_q = len(self.questions) if self.questions else 1
        for cat, cnt in sorted_cats[:5]:
            pct = int((cnt / total_q) * 100)
            row2 = QHBoxLayout()
            dot = QLabel("●")
            dot.setStyleSheet(f"font-size:8px;color:{_c('text_dim')};background:transparent;border:none;")
            row2.addWidget(dot)
            cl = QLabel(cat)
            cl.setStyleSheet(f"font-size:12px;color:{_c('text_pri')};background:transparent;border:none;")
            row2.addWidget(cl)
            row2.addStretch()
            cnl = QLabel(f"{cnt} q. ({pct}%)")
            cnl.setStyleSheet(f"font-size:11px;color:{_c('text_mut')};background:transparent;border:none;")
            row2.addWidget(cnl)
            cats_card.layout().addLayout(row2)
        cats_card.layout().addStretch()
        cr.addWidget(cats_card, 1)
        outer.addLayout(cr)
        outer.addStretch()

class SimuladoPage(AnimatedPage):
    def __init__(self, questions, parent=None):
        super().__init__(parent)
        self.all_q = questions
        self.questions = []
        self.idx = 0
        self.score = 0
        self.answered = False
        self._build()
    def refresh_questions(self, q): self.all_q = q
    def _build(self):
        self.stack = QStackedWidget()
        self.stack.setStyleSheet("background:transparent;border:none;")
        self.lay.addWidget(self.stack)
        self._start_page()
        self._q_page()
        self._result_page()
        self.stack.setCurrentIndex(0)
    def _start_page(self):
        p = QWidget()
        p.setStyleSheet("background:transparent;")
        l = QVBoxLayout(p)
        l.setAlignment(Qt.AlignCenter)
        l.setSpacing(14)
        ic = QLabel("📝")
        ic.setStyleSheet(f"font-size:32px;background:transparent;color:{_c('text_mut')};border:none;")
        ic.setAlignment(Qt.AlignCenter)
        l.addWidget(ic)
        t = QLabel("Simulado Local")
        t.setStyleSheet(f"font-size:20px;font-weight:500;color:{_c('text_pri')};border:none;background:transparent;")
        t.setAlignment(Qt.AlignCenter)
        l.addWidget(t)
        d = QLabel(f"Sessão de {_CFG.get('questions_per_round', 5)} questões geradas offline.")
        d.setStyleSheet(f"font-size:12px;color:{_c('text_mut')};border:none;background:transparent;")
        d.setAlignment(Qt.AlignCenter)
        l.addWidget(d)
        l.addSpacing(16)
        b = PBtn("Iniciar Conexão")
        b.setFixedWidth(160)
        b.clicked.connect(self._start)
        l.addWidget(b, alignment=Qt.AlignCenter)
        self.stack.addWidget(p)
    def _q_page(self):
        p = QWidget()
        p.setStyleSheet("background:transparent;")
        lay = QVBoxLayout(p)
        lay.setContentsMargins(32, 28, 32, 20)
        lay.setSpacing(16)
        hr = QHBoxLayout()
        self.prog_lbl = QLabel("Progresso: 1/5")
        self.prog_lbl.setStyleSheet(f"font-size:11px;font-weight:500;color:{_c('text_mut')};border:none;background:transparent;")
        hr.addWidget(self.prog_lbl)
        hr.addStretch()
        self.cat_lbl = QLabel()
        self.cat_lbl.setStyleSheet(f"font-size:10px;color:{_c('text_mut')};background:{_c('surface')};padding:3px 8px;border-radius:6px;border:1px solid {_c('border')};")
        hr.addWidget(self.cat_lbl)
        lay.addLayout(hr)
        self.pbar = PBar(5, 0)
        lay.addWidget(self.pbar)
        sc = QScrollArea()
        sc.setWidgetResizable(True)
        sc.setStyleSheet("background:transparent;border:none;")
        sw = QWidget()
        sw.setStyleSheet("background:transparent;")
        sl = QVBoxLayout(sw)
        sl.setContentsMargins(0, 6, 8, 6)
        sl.setSpacing(14)
        qc = Card(pad=18)
        self.q_lbl = QLabel()
        self.q_lbl.setWordWrap(True)
        self.q_lbl.setStyleSheet(f"font-size:14px;font-weight:400;color:{_c('text_pri')};line-height:1.5;border:none;background:transparent;")
        qc.layout().addWidget(self.q_lbl)
        sl.addWidget(qc)
        self.opts = QVBoxLayout()
        self.opts.setSpacing(10)
        sl.addLayout(self.opts)
        self.fb = Card(accent=True, pad=16)
        self.fb.setVisible(False)
        fh = QHBoxLayout()
        fl = QLabel("Log de Resposta")
        fl.setStyleSheet(f"font-size:11px;font-weight:600;color:{_c('accent')};border:none;background:transparent;")
        fh.addWidget(fl)
        fh.addStretch()
        self.fb.layout().addLayout(fh)
        self.fb_txt = QLabel()
        self.fb_txt.setWordWrap(True)
        self.fb_txt.setStyleSheet(f"font-size:12px;color:{_c('text_pri')};line-height:1.5;border:none;background:transparent;")
        self.fb.layout().addWidget(self.fb_txt)
        sl.addWidget(self.fb)
        sl.addStretch()
        sc.setWidget(sw)
        lay.addWidget(sc, 1)
        ft = QHBoxLayout()
        ft.addStretch()
        self.next_btn = PBtn("Avançar")
        self.next_btn.setFixedWidth(130)
        self.next_btn.setVisible(False)
        self.next_btn.clicked.connect(self._next)
        ft.addWidget(self.next_btn)
        lay.addLayout(ft)
        self.stack.addWidget(p)
    def _result_page(self):
        p = QWidget()
        p.setStyleSheet("background:transparent;")
        l = QVBoxLayout(p)
        l.setAlignment(Qt.AlignCenter)
        l.setSpacing(14)
        self.r_ic = QLabel("✓")
        self.r_ic.setStyleSheet(f"font-size:40px;color:{_c('text_mut')};background:transparent;border:none;")
        self.r_ic.setAlignment(Qt.AlignCenter)
        l.addWidget(self.r_ic)
        self.r_sc = QLabel()
        self.r_sc.setStyleSheet(f"font-size:36px;font-weight:300;color:{_c('text_pri')};border:none;background:transparent;")
        self.r_sc.setAlignment(Qt.AlignCenter)
        l.addWidget(self.r_sc)
        self.r_mg = QLabel()
        self.r_mg.setStyleSheet(f"font-size:13px;color:{_c('text_mut')};border:none;background:transparent;")
        self.r_mg.setAlignment(Qt.AlignCenter)
        l.addWidget(self.r_mg)
        l.addSpacing(16)
        rb = PBtn("Finalizar Sessão")
        rb.setFixedWidth(150)
        rb.clicked.connect(self._start)
        l.addWidget(rb, alignment=Qt.AlignCenter)
        self.stack.addWidget(p)
    def _start(self):
        cnt = _CFG.get("questions_per_round", 5)
        if not self.all_q: return
        self.questions = random.sample(self.all_q, min(cnt, len(self.all_q)))
        self.idx = 0
        self.score = 0
        self.answered = False
        self._show_q()
    def _show_q(self):
        self.answered = False
        for i in reversed(range(self.opts.count())):
            w = self.opts.itemAt(i).widget()
            if w: w.deleteLater()
        q = self.questions[self.idx]
        total = len(self.questions)
        self.prog_lbl.setText(f"Progresso: {self.idx+1}/{total}")
        self.pbar.total = total
        self.pbar.set_progress(self.idx)
        self.cat_lbl.setText(q.get("categoria", "[Geral]"))
        self.q_lbl.setText(q["pergunta"])
        self.fb.setVisible(False)
        self.next_btn.setVisible(False)
        self.opt_btns = []
        for i, op in enumerate(q["opcoes"]):
            b = OptBtn(op, i)
            b.clicked.connect(lambda _, ix=i: self._answer(ix))
            self.opts.addWidget(b)
            self.opt_btns.append(b)
        self.stack.setCurrentIndex(1)
        fade_in_widget(self.stack.widget(1))
    def _answer(self, chosen):
        if self.answered: return
        self.answered = True
        q = self.questions[self.idx]
        correct = q["correta"]
        for i, b in enumerate(self.opt_btns):
            b.setEnabled(False)
            b.set_state("correct" if i == correct else ("wrong" if i == chosen and chosen != correct else "disabled"))
        if chosen == correct: self.score += 1
        txt = q.get("explicacao", "") + (f"\n\n[Atenção]: {q.get('pegadinha', '')}" if q.get("pegadinha") else "")
        self.fb_txt.setText(txt)
        self.fb.setVisible(True)
        self.next_btn.setText("Encerrar" if self.idx == len(self.questions) - 1 else "Avançar")
        self.next_btn.setVisible(True)
        fade_in_widget(self.fb, 250)
        fade_in_widget(self.next_btn, 250)
    def _next(self):
        self.idx += 1
        if self.idx >= len(self.questions): self._result()
        else: self._show_q()
    def _result(self):
        total = len(self.questions)
        pct = self.score / total * 100
        self.r_ic.setText("✓" if pct >= 70 else "✗")
        self.r_sc.setText(f"Score: {self.score}/{total}")
        self.r_mg.setText(f"Status: {'Aprovado' if pct>=70 else 'Reprovado'}  ({pct:.0f}%)")
        self.stack.setCurrentIndex(2)
        fade_in_widget(self.stack.widget(2))

class SimuladoIAPage(AnimatedPage):
    questions_saved = Signal(list)
    work_started = Signal()
    work_finished = Signal()
    def __init__(self, questions, parent=None):
        super().__init__(parent)
        self.all_q = questions
        self.generated = []
        self.idx = 0
        self.score = 0
        self.answered = False
        self._save_flag = True
        self._build()
    def refresh_questions(self, q): self.all_q = q
    def _build(self):
        self.stack = QStackedWidget()
        self.stack.setStyleSheet("background:transparent;border:none;")
        self.lay.addWidget(self.stack)
        self._config_page()
        self._loading_page()
        self._q_page()
        self._result_page()
        self.stack.setCurrentIndex(0)
    def _config_page(self):
        p = QWidget()
        p.setStyleSheet("background:transparent;")
        lay = QVBoxLayout(p)
        lay.setContentsMargins(32, 32, 32, 32)
        lay.setSpacing(18)
        ht = QLabel("Simulado Assistido por IA")
        ht.setStyleSheet(f"font-size:20px;font-weight:500;color:{_c('text_pri')};border:none;background:transparent;")
        lay.addWidget(ht)
        sub = QLabel("O motor Gemini analisará o banco local para gerar conteúdo inédito.")
        sub.setStyleSheet(f"font-size:12px;color:{_c('text_mut')};border:none;background:transparent;")
        lay.addWidget(sub)
        key_ok = bool(_CFG.get("gemini_api_key", ""))
        ic = Card(accent=key_ok, pad=14)
        if not key_ok: ic.setStyleSheet(f"QFrame{{background:{_c('surface')};border-radius:12px;border:1px solid {_c('orange')};}}")
        kr = QHBoxLayout()
        kl = QLabel("Status: API Key Válida" if key_ok else "Aviso: API Key não configurada")
        kl.setStyleSheet(f"font-size:12px;font-weight:500;color:{_c('accent') if key_ok else _c('orange')};border:none;background:transparent;")
        kr.addWidget(kl)
        kr.addStretch()
        ml = QLabel(f"Node: {_CFG.get('gemini_model','gemini-flash-lite-latest')}")
        ml.setStyleSheet(f"font-size:11px;color:{_c('text_dim')};border:none;background:transparent;")
        kr.addWidget(ml)
        ic.layout().addLayout(kr)
        lay.addWidget(ic)
        oc = Card(pad=18)
        ol = QLabel("Parâmetros de Geração")
        ol.setStyleSheet(f"font-size:13px;font-weight:500;color:{_c('text_pri')};border:none;background:transparent;")
        oc.layout().addWidget(ol)
        oc.layout().addWidget(Sep())
        qr = QHBoxLayout()
        ql = QLabel("Volume de questões:")
        ql.setStyleSheet(f"font-size:12px;color:{_c('text_mut')};border:none;background:transparent;")
        ql.setFixedWidth(160)
        qr.addWidget(ql)
        qr.addStretch()
        self.ia_spin = QSpinBox()
        self.ia_spin.setRange(1, 20)
        self.ia_spin.setValue(_CFG.get("questions_per_round", 5))
        self.ia_spin.setFixedWidth(70)
        qr.addWidget(self.ia_spin)
        oc.layout().addLayout(qr)
        sr = QHBoxLayout()
        sl = QLabel("Persistir no disco local:")
        sl.setStyleSheet(f"font-size:12px;color:{_c('text_mut')};border:none;background:transparent;")
        sl.setFixedWidth(160)
        sr.addWidget(sl)
        sr.addStretch()
        self.save_yes = TogBtn("Sim")
        self.save_yes.setChecked(True)
        self.save_no = TogBtn("Não")
        self.save_yes.clicked.connect(lambda: self.save_no.setChecked(False))
        self.save_no.clicked.connect(lambda: self.save_yes.setChecked(False))
        sr.addWidget(self.save_yes)
        sr.addWidget(self.save_no)
        oc.layout().addLayout(sr)
        lay.addWidget(oc)
        lay.addStretch()
        sb = PBtn("Executar Geração", color=_c("accent"))
        sb.setFixedWidth(180)
        sb.clicked.connect(self._generate)
        lay.addWidget(sb, alignment=Qt.AlignCenter)
        self.stack.addWidget(p)
    def _loading_page(self):
        p = QWidget()
        p.setStyleSheet("background:transparent;")
        lay = QVBoxLayout(p)
        lay.setAlignment(Qt.AlignCenter)
        lay.setSpacing(16)
        self.dot = PulseDot()
        lay.addWidget(self.dot, alignment=Qt.AlignCenter)
        tl = QLabel("Processando requisição...")
        tl.setStyleSheet(f"font-size:16px;font-weight:400;color:{_c('text_pri')};border:none;background:transparent;")
        tl.setAlignment(Qt.AlignCenter)
        lay.addWidget(tl)
        self.l_st = QLabel("Aguardando resposta do servidor...")
        self.l_st.setStyleSheet(f"font-size:11px;color:{_c('text_mut')};border:none;background:transparent;")
        self.l_st.setAlignment(Qt.AlignCenter)
        lay.addWidget(self.l_st)
        self.stack.addWidget(p)
    def _q_page(self):
        p = QWidget()
        p.setStyleSheet("background:transparent;")
        lay = QVBoxLayout(p)
        lay.setContentsMargins(32, 28, 32, 20)
        lay.setSpacing(14)
        hr = QHBoxLayout()
        self.ia_plbl = QLabel()
        self.ia_plbl.setStyleSheet(f"font-size:11px;font-weight:500;color:{_c('text_mut')};border:none;background:transparent;")
        hr.addWidget(self.ia_plbl)
        hr.addStretch()
        b2 = QLabel("[IA Generated]")
        b2.setStyleSheet(f"font-size:10px;color:{_c('accent')};border:none;background:transparent;")
        hr.addWidget(b2)
        lay.addLayout(hr)
        self.ia_pb = PBar(5, 0)
        lay.addWidget(self.ia_pb)
        sc = QScrollArea()
        sc.setWidgetResizable(True)
        sc.setStyleSheet("background:transparent;border:none;")
        sw = QWidget()
        sw.setStyleSheet("background:transparent;")
        sl = QVBoxLayout(sw)
        sl.setContentsMargins(0, 6, 8, 6)
        sl.setSpacing(14)
        qc = Card(pad=18)
        self.ia_qlbl = QLabel()
        self.ia_qlbl.setWordWrap(True)
        self.ia_qlbl.setStyleSheet(f"font-size:14px;font-weight:400;color:{_c('text_pri')};line-height:1.5;border:none;background:transparent;")
        qc.layout().addWidget(self.ia_qlbl)
        sl.addWidget(qc)
        self.ia_opts = QVBoxLayout()
        self.ia_opts.setSpacing(10)
        sl.addLayout(self.ia_opts)
        self.ia_fb = Card(accent=True, pad=16)
        self.ia_fb.setVisible(False)
        fh = QHBoxLayout()
        fl = QLabel("Log de Análise (IA)")
        fl.setStyleSheet(f"font-size:11px;font-weight:600;color:{_c('accent')};border:none;background:transparent;")
        fh.addWidget(fl)
        fh.addStretch()
        self.ia_fb.layout().addLayout(fh)
        self.ia_ftxt = QLabel()
        self.ia_ftxt.setWordWrap(True)
        self.ia_ftxt.setStyleSheet(f"font-size:12px;color:{_c('text_pri')};line-height:1.5;border:none;background:transparent;")
        self.ia_fb.layout().addWidget(self.ia_ftxt)
        sl.addWidget(self.ia_fb)
        sl.addStretch()
        sc.setWidget(sw)
        lay.addWidget(sc, 1)
        ft = QHBoxLayout()
        ft.addStretch()
        self.ia_nb = PBtn("Avançar")
        self.ia_nb.setFixedWidth(130)
        self.ia_nb.setVisible(False)
        self.ia_nb.clicked.connect(self._ia_next)
        ft.addWidget(self.ia_nb)
        lay.addLayout(ft)
        self.stack.addWidget(p)
    def _result_page(self):
        p = QWidget()
        p.setStyleSheet("background:transparent;")
        l = QVBoxLayout(p)
        l.setAlignment(Qt.AlignCenter)
        l.setSpacing(14)
        self.ia_ric = QLabel("✓")
        self.ia_ric.setStyleSheet("font-size:40px;background:transparent;border:none;")
        self.ia_ric.setAlignment(Qt.AlignCenter)
        l.addWidget(self.ia_ric)
        self.ia_rsc = QLabel()
        self.ia_rsc.setStyleSheet(f"font-size:36px;font-weight:300;color:{_c('text_pri')};border:none;background:transparent;")
        self.ia_rsc.setAlignment(Qt.AlignCenter)
        l.addWidget(self.ia_rsc)
        self.ia_rmg = QLabel()
        self.ia_rmg.setStyleSheet(f"font-size:13px;color:{_c('text_mut')};border:none;background:transparent;")
        self.ia_rmg.setAlignment(Qt.AlignCenter)
        l.addWidget(self.ia_rmg)
        self.ia_slbl = QLabel()
        self.ia_slbl.setStyleSheet(f"font-size:10px;color:{_c('accent')};border:none;background:transparent;")
        self.ia_slbl.setAlignment(Qt.AlignCenter)
        l.addWidget(self.ia_slbl)
        l.addSpacing(16)
        nb2 = PBtn("Retornar")
        nb2.setFixedWidth(140)
        nb2.clicked.connect(lambda: self.stack.setCurrentIndex(0))
        l.addWidget(nb2, alignment=Qt.AlignCenter)
        self.stack.addWidget(p)
    def _generate(self):
        key = _CFG.get("gemini_api_key", "")
        if not key:
            self.l_st.setText("Error: API Key missing.")
            self.stack.setCurrentIndex(1)
            QTimer.singleShot(2000, lambda: self.stack.setCurrentIndex(0))
            return
        self.stack.setCurrentIndex(1)
        self.dot.set_active(_c("accent"), True)
        self.l_st.setText("Iniciando conexão...")
        self.work_started.emit()
        self._save_flag = self.save_yes.isChecked()
        cnt = self.ia_spin.value()
        self._worker = GeminiWorker(key, _CFG.get("gemini_model", "gemini-flash-lite-latest"), self.all_q, cnt)
        self._worker.done.connect(self._on_done)
        self._worker.error.connect(self._on_err)
        self._worker.status.connect(lambda s: QTimer.singleShot(0, lambda: self.l_st.setText(s)))
        self._thread = threading.Thread(target=self._worker.run, daemon=True)
        self._thread.start()
    def _on_done(self, qs):
        self.work_finished.emit()
        self.dot.set_active(_c("text_dim"), False)
        self.generated = qs
        self.idx = 0
        self.score = 0
        self.answered = False
        if self._save_flag and qs:
            self.all_q.extend(qs)
            save_questions(self.all_q)
            self.questions_saved.emit(self.all_q)
        QTimer.singleShot(0, self._show_ia_q)
    def _on_err(self, msg):
        self.work_finished.emit()
        self.dot.set_active(_c("red"), False)
        QTimer.singleShot(0, lambda: (self.l_st.setText(f"Exception: {msg[:100]}"), QTimer.singleShot(3500, lambda: self.stack.setCurrentIndex(0))))
    def _show_ia_q(self):
        self.answered = False
        for i in reversed(range(self.ia_opts.count())):
            w = self.ia_opts.itemAt(i).widget()
            if w: w.deleteLater()
        q = self.generated[self.idx]
        total = len(self.generated)
        self.ia_plbl.setText(f"Sessão IA: {self.idx+1}/{total}")
        self.ia_pb.total = total
        self.ia_pb.set_progress(self.idx)
        self.ia_qlbl.setText(q["pergunta"])
        self.ia_fb.setVisible(False)
        self.ia_nb.setVisible(False)
        self.ia_opt_btns = []
        for i, op in enumerate(q["opcoes"]):
            b = OptBtn(op, i)
            b.clicked.connect(lambda _, ix=i: self._ia_ans(ix))
            self.ia_opts.addWidget(b)
            self.ia_opt_btns.append(b)
        self.stack.setCurrentIndex(2)
        fade_in_widget(self.stack.widget(2))
    def _ia_ans(self, chosen):
        if self.answered: return
        self.answered = True
        q = self.generated[self.idx]
        correct = q["correta"]
        for i, b in enumerate(self.ia_opt_btns):
            b.setEnabled(False)
            b.set_state("correct" if i == correct else ("wrong" if i == chosen and chosen != correct else "disabled"))
        if chosen == correct: self.score += 1
        txt = q.get("explicacao", "") + (f"\n\n[Warning]: {q['pegadinha']}" if q.get("pegadinha", "") else "")
        self.ia_ftxt.setText(txt)
        self.ia_fb.setVisible(True)
        self.ia_nb.setText("Encerrar" if self.idx == len(self.generated) - 1 else "Avançar")
        self.ia_nb.setVisible(True)
        fade_in_widget(self.ia_fb, 250)
        fade_in_widget(self.ia_nb, 250)
    def _ia_next(self):
        self.idx += 1
        if self.idx >= len(self.generated): self._ia_result()
        else: self._show_ia_q()
    def _ia_result(self):
        total = len(self.generated)
        pct = self.score / total * 100
        self.ia_ric.setText("✓" if pct >= 70 else "✗")
        self.ia_rsc.setText(f"Score: {self.score}/{total}")
        self.ia_rmg.setText(f"Status: {'Aprovado' if pct>=70 else 'Reprovado'}  ({pct:.0f}%)")
        self.ia_slbl.setText(f"[{len(self.generated)} registros salvos]" if self._save_flag else "[Modo volátil - nada salvo]")
        self.stack.setCurrentIndex(3)
        fade_in_widget(self.stack.widget(3))

class ConfigPage(AnimatedPage):
    settings_changed = Signal()
    def __init__(self, parent=None):
        super().__init__(parent)
        self._build()
    def _build(self):
        outer = self.lay
        outer.setContentsMargins(32, 32, 32, 32)
        outer.setSpacing(20)
        ht = QLabel("Configurações do Sistema")
        ht.setStyleSheet(f"font-size:20px;font-weight:500;color:{_c('text_pri')};border:none;background:transparent;")
        outer.addWidget(ht)
        sc = QScrollArea()
        sc.setWidgetResizable(True)
        sc.setStyleSheet("background:transparent;border:none;")
        sw = QWidget()
        sw.setStyleSheet("background:transparent;")
        sl = QVBoxLayout(sw)
        sl.setContentsMargins(0, 0, 8, 0)
        sl.setSpacing(16)
        ap = Card(pad=18)
        ap.layout().setSpacing(12)
        ap.layout().addWidget(self._sec_title("Aparência & Interface"))
        ap.layout().addWidget(Sep())
        tr = QHBoxLayout()
        tl = QLabel("Tema do Sistema:")
        tl.setStyleSheet(self._lbl_style())
        tl.setFixedWidth(140)
        tr.addWidget(tl)
        self.th_dark = TogBtn("Escuro")
        self.th_light = TogBtn("Claro")
        self.th_dark.setChecked(_CFG.get("theme", "dark") == "dark")
        self.th_light.setChecked(_CFG.get("theme", "dark") == "light")
        self.th_dark.clicked.connect(lambda: self.th_light.setChecked(False))
        self.th_light.clicked.connect(lambda: self.th_dark.setChecked(False))
        tr.addWidget(self.th_dark)
        tr.addWidget(self.th_light)
        tr.addStretch()
        ap.layout().addLayout(tr)
        fr = QHBoxLayout()
        fl = QLabel("Fonte / Tamanho:")
        fl.setStyleSheet(self._lbl_style())
        fl.setFixedWidth(140)
        fr.addWidget(fl)
        self.font_btn = GBtn(f"{_CFG.get('font_family','Inter')}  {_CFG.get('font_size',13)}px")
        self.font_btn.setFixedWidth(180)
        self.font_btn.clicked.connect(self._pick_font)
        fr.addWidget(self.font_btn)
        fr.addStretch()
        ap.layout().addLayout(fr)
        sl.addWidget(ap)
        sm = Card(pad=18)
        sm.layout().setSpacing(12)
        sm.layout().addWidget(self._sec_title("Parâmetros de Sessão"))
        sm.layout().addWidget(Sep())
        qr = QHBoxLayout()
        ql = QLabel("Bloco de questões:")
        ql.setStyleSheet(self._lbl_style())
        ql.setFixedWidth(140)
        qr.addWidget(ql)
        self.q_spin = QSpinBox()
        self.q_spin.setRange(1, 50)
        self.q_spin.setValue(_CFG.get("questions_per_round", 5))
        self.q_spin.setFixedWidth(70)
        qr.addWidget(self.q_spin)
        qr.addStretch()
        sm.layout().addLayout(qr)
        sl.addWidget(sm)
        gm = Card(pad=18)
        gm.layout().setSpacing(12)
        gm.layout().addWidget(self._sec_title("Integração Gemini API"))
        gm.layout().addWidget(Sep())
        kr = QHBoxLayout()
        kl = QLabel("Token (API Key):")
        kl.setStyleSheet(self._lbl_style())
        kl.setFixedWidth(140)
        kr.addWidget(kl)
        self.api_input = QLineEdit()
        self.api_input.setPlaceholderText("Insira a chave...")
        self.api_input.setEchoMode(QLineEdit.Password)
        self.api_input.setText(_CFG.get("gemini_api_key", ""))
        kr.addWidget(self.api_input, 1)
        sb2 = GBtn("👁")
        sb2.setFixedWidth(36)
        sb2.setFixedHeight(34)
        sb2.clicked.connect(lambda: self.api_input.setEchoMode(QLineEdit.Normal if self.api_input.echoMode() == QLineEdit.Password else QLineEdit.Password))
        kr.addWidget(sb2)
        gm.layout().addLayout(kr)
        mr = QHBoxLayout()
        ml2 = QLabel("Node/Modelo:")
        ml2.setStyleSheet(self._lbl_style())
        ml2.setFixedWidth(140)
        mr.addWidget(ml2)
        self.model_cb = QComboBox()
        self.model_cb.setFixedWidth(180)
        for m in GEMINI_MODELS: self.model_cb.addItem(m)
        cidx = self.model_cb.findText(_CFG.get("gemini_model", "gemini-flash-lite-latest"))
        if cidx >= 0: self.model_cb.setCurrentIndex(cidx)
        mr.addWidget(self.model_cb)
        mr.addStretch()
        gm.layout().addLayout(mr)
        sl.addWidget(gm)
        sl.addStretch()
        sc.setWidget(sw)
        outer.addWidget(sc, 1)
        foot = QHBoxLayout()
        foot.addStretch()
        self.save_btn = PBtn("Gravar Alterações", color=_c("accent"))
        self.save_btn.setFixedWidth(160)
        self.save_btn.clicked.connect(self._save)
        foot.addWidget(self.save_btn)
        outer.addLayout(foot)
    def _sec_title(self, t):
        l = QLabel(t)
        l.setStyleSheet(f"font-size:12px;font-weight:600;color:{_c('text_pri')};border:none;background:transparent;")
        return l
    def _lbl_style(self): return f"font-size:12px;color:{_c('text_mut')};border:none;background:transparent;"
    def _pick_font(self):
        ok, font = QFontDialog.getFont()
        if ok:
            self.font_btn.setText(f"{font.family()}  {font.pointSize()}px")
            _CFG["font_family"] = font.family()
            _CFG["font_size"] = font.pointSize()
    def _save(self):
        _CFG["theme"] = "light" if self.th_light.isChecked() else "dark"
        _CFG["questions_per_round"] = self.q_spin.value()
        _CFG["gemini_api_key"] = self.api_input.text().strip()
        _CFG["gemini_model"] = self.model_cb.currentText()
        save_config()
        self.save_btn.setText("Gravado!")
        QTimer.singleShot(800, lambda: self.settings_changed.emit())
